spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
cors:
  allowed-origins: "https://thankful-tree-0361b300f.4.azurestaticapps.net,http://localhost:5173,http://localhost:4173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"


  